=== ASSASSIN (19) ===
https://raw.githubusercontent.com/RennyMaharani27/Assassin/main/Aamon.jpg
https://raw.githubusercontent.com/RennyMaharani27/Assassin/main/benedetta.jpg
https://raw.githubusercontent.com/RennyMaharani27/Assassin/main/Fanny.jpg
https://raw.githubusercontent.com/RennyMaharani27/Assassin/main/Gusion.jpg
https://raw.githubusercontent.com/RennyMaharani27/Assassin/main/Hanzo.jpg
https://raw.githubusercontent.com/RennyMaharani27/Assassin/main/Harley.png
https://raw.githubusercontent.com/RennyMaharani27/Assassin/main/Hayabusa.jpg
https://raw.githubusercontent.com/RennyMaharani27/Assassin/main/Helcurt.jpg
https://raw.githubusercontent.com/RennyMaharani27/Assassin/main/Hirara.png
https://raw.githubusercontent.com/RennyMaharani27/Assassin/main/Joy.png
https://raw.githubusercontent.com/RennyMaharani27/Assassin/main/Julian.jpg
https://raw.githubusercontent.com/RennyMaharani27/Assassin/main/Karina.jpg
https://raw.githubusercontent.com/RennyMaharani27/Assassin/main/Lancelot.jpg
https://raw.githubusercontent.com/RennyMaharani27/Assassin/main/Ling.jpg
https://raw.githubusercontent.com/RennyMaharani27/Assassin/main/Natalia.jpg
https://raw.githubusercontent.com/RennyMaharani27/Assassin/main/Nolan.png
https://raw.githubusercontent.com/RennyMaharani27/Assassin/main/Saber.jpg
https://raw.githubusercontent.com/RennyMaharani27/Assassin/main/Suyouu.png
https://raw.githubusercontent.com/RennyMaharani27/Assassin/main/Yi%20Sun%20Shin.png

=== FIGHTER (37) ===
https://raw.githubusercontent.com/RennyMaharani27/Fighter/main/Aldous.jpg
https://raw.githubusercontent.com/RennyMaharani27/Fighter/main/Alpha.jpg
https://raw.githubusercontent.com/RennyMaharani27/Fighter/main/Alucard.jpg
https://raw.githubusercontent.com/RennyMaharani27/Fighter/main/Argus.jpg
https://raw.githubusercontent.com/RennyMaharani27/Fighter/main/Arlott.png
https://raw.githubusercontent.com/RennyMaharani27/Fighter/main/Aulus.png
https://raw.githubusercontent.com/RennyMaharani27/Fighter/main/Badang.jpg
https://raw.githubusercontent.com/RennyMaharani27/Fighter/main/Balmond.png
https://raw.githubusercontent.com/RennyMaharani27/Fighter/main/Bane.png
https://raw.githubusercontent.com/RennyMaharani27/Fighter/main/Barats.png
https://raw.githubusercontent.com/RennyMaharani27/Fighter/main/Chou.jpg
https://raw.githubusercontent.com/RennyMaharani27/Fighter/main/Cici.jpg
https://raw.githubusercontent.com/RennyMaharani27/Fighter/main/Dyrroth.png
https://raw.githubusercontent.com/RennyMaharani27/Fighter/main/Freya.png
https://raw.githubusercontent.com/RennyMaharani27/Fighter/main/Gatot%20Kaca.jpg
https://raw.githubusercontent.com/RennyMaharani27/Fighter/main/Guinevere.jpg
https://raw.githubusercontent.com/RennyMaharani27/Fighter/main/Jawhead.jpg
https://raw.githubusercontent.com/RennyMaharani27/Fighter/main/Julian.jpg
https://raw.githubusercontent.com/RennyMaharani27/Fighter/main/Khaleed.png
https://raw.githubusercontent.com/RennyMaharani27/Fighter/main/Leomord.jpg
https://raw.githubusercontent.com/RennyMaharani27/Fighter/main/Lukas.jpg
https://raw.githubusercontent.com/RennyMaharani27/Fighter/main/Martis.png
https://raw.githubusercontent.com/RennyMaharani27/Fighter/main/Masha.png
https://raw.githubusercontent.com/RennyMaharani27/Fighter/main/Minsitthar.png
https://raw.githubusercontent.com/RennyMaharani27/Fighter/main/Paquito.png
https://raw.githubusercontent.com/RennyMaharani27/Fighter/main/Poveus.png
https://raw.githubusercontent.com/RennyMaharani27/Fighter/main/Roger.jpg
https://raw.githubusercontent.com/RennyMaharani27/Fighter/main/Ruby.jpg
https://raw.githubusercontent.com/RennyMaharani27/Fighter/main/Silvanna.jpg
https://raw.githubusercontent.com/RennyMaharani27/Fighter/main/Sora.png
https://raw.githubusercontent.com/RennyMaharani27/Fighter/main/Sun.jpg
https://raw.githubusercontent.com/RennyMaharani27/Fighter/main/Terizla.png
https://raw.githubusercontent.com/RennyMaharani27/Fighter/main/Thamuz.png
https://raw.githubusercontent.com/RennyMaharani27/Fighter/main/X%20Borg.jpg
https://raw.githubusercontent.com/RennyMaharani27/Fighter/main/Yin.png
https://raw.githubusercontent.com/RennyMaharani27/Fighter/main/Yu%20Zhong.jpg
https://raw.githubusercontent.com/RennyMaharani27/Fighter/main/Zilong.jpg

=== MAGE (27) ===
https://raw.githubusercontent.com/RennyMaharani27/Mage/main/Aurora.jpg
https://raw.githubusercontent.com/RennyMaharani27/Mage/main/Chang'e.jpg
https://raw.githubusercontent.com/RennyMaharani27/Mage/main/Cyclops.jpg
https://raw.githubusercontent.com/RennyMaharani27/Mage/main/Esmeralda.jpg
https://raw.githubusercontent.com/RennyMaharani27/Mage/main/Eudora.png
https://raw.githubusercontent.com/RennyMaharani27/Mage/main/Faramis.jpg
https://raw.githubusercontent.com/RennyMaharani27/Mage/main/Gord.jpg
https://raw.githubusercontent.com/RennyMaharani27/Mage/main/Harith.jpg
https://raw.githubusercontent.com/RennyMaharani27/Mage/main/Kaditta.png
https://raw.githubusercontent.com/RennyMaharani27/Mage/main/Kagura.jpg
https://raw.githubusercontent.com/RennyMaharani27/Mage/main/Lunox.jpg
https://raw.githubusercontent.com/RennyMaharani27/Mage/main/Luo%20Yi.png
https://raw.githubusercontent.com/RennyMaharani27/Mage/main/Lylia.png
https://raw.githubusercontent.com/RennyMaharani27/Mage/main/Nana.jpg
https://raw.githubusercontent.com/RennyMaharani27/Mage/main/Novaria.jpg
https://raw.githubusercontent.com/RennyMaharani27/Mage/main/Odette.jpg
https://raw.githubusercontent.com/RennyMaharani27/Mage/main/Pharsa.jpg
https://raw.githubusercontent.com/RennyMaharani27/Mage/main/Selena.png
https://raw.githubusercontent.com/RennyMaharani27/Mage/main/Vale.jpg
https://raw.githubusercontent.com/RennyMaharani27/Mage/main/Valentina.png
https://raw.githubusercontent.com/RennyMaharani27/Mage/main/Valir.png
https://raw.githubusercontent.com/RennyMaharani27/Mage/main/Vexana.jpg
https://raw.githubusercontent.com/RennyMaharani27/Mage/main/Xavier.jpg
https://raw.githubusercontent.com/RennyMaharani27/Mage/main/Yve.png
https://raw.githubusercontent.com/RennyMaharani27/Mage/main/Zetian.jpg
https://raw.githubusercontent.com/RennyMaharani27/Mage/main/Zhask.png
https://raw.githubusercontent.com/RennyMaharani27/Mage/main/Zhuxin.jpg

=== MARKSMAN (20) ===
https://raw.githubusercontent.com/RennyMaharani27/Marksman/main/Beatrix.jpg
https://raw.githubusercontent.com/RennyMaharani27/Marksman/main/Brody.jpg
https://raw.githubusercontent.com/RennyMaharani27/Marksman/main/Bruno.jpg
https://raw.githubusercontent.com/RennyMaharani27/Marksman/main/Claude.jpg
https://raw.githubusercontent.com/RennyMaharani27/Marksman/main/Clint.jpg
https://raw.githubusercontent.com/RennyMaharani27/Marksman/main/Granger.jpg
https://raw.githubusercontent.com/RennyMaharani27/Marksman/main/Hanabi.jpg
https://raw.githubusercontent.com/RennyMaharani27/Marksman/main/Irithel.png
https://raw.githubusercontent.com/RennyMaharani27/Marksman/main/Ixia.png
https://raw.githubusercontent.com/RennyMaharani27/Marksman/main/Karrie.png
https://raw.githubusercontent.com/RennyMaharani27/Marksman/main/Kimmy.png
https://raw.githubusercontent.com/RennyMaharani27/Marksman/main/Layla.jpg
https://raw.githubusercontent.com/RennyMaharani27/Marksman/main/Lesley.jpg
https://raw.githubusercontent.com/RennyMaharani27/Marksman/main/Melissa.jpg
https://raw.githubusercontent.com/RennyMaharani27/Marksman/main/Miya.jpg
https://raw.githubusercontent.com/RennyMaharani27/Marksman/main/Moskov.png
https://raw.githubusercontent.com/RennyMaharani27/Marksman/main/Nolan.jpg
https://raw.githubusercontent.com/RennyMaharani27/Marksman/main/Obsidia.png
https://raw.githubusercontent.com/RennyMaharani27/Marksman/main/Popol%20And%20Kupa.jpg
https://raw.githubusercontent.com/RennyMaharani27/Marksman/main/Wanwan.jpg

=== SUPPORT (13) ===
https://raw.githubusercontent.com/RennyMaharani27/Support/main/Angela.jpg
https://raw.githubusercontent.com/RennyMaharani27/Support/main/Carmilla.png
https://raw.githubusercontent.com/RennyMaharani27/Support/main/Chip.png
https://raw.githubusercontent.com/RennyMaharani27/Support/main/Diggie.png
https://raw.githubusercontent.com/RennyMaharani27/Support/main/Estes.jpg
https://raw.githubusercontent.com/RennyMaharani27/Support/main/Faramis.jpg
https://raw.githubusercontent.com/RennyMaharani27/Support/main/Floryn.jpg
https://raw.githubusercontent.com/RennyMaharani27/Support/main/Kaja.png
https://raw.githubusercontent.com/RennyMaharani27/Support/main/Kalea.png
https://raw.githubusercontent.com/RennyMaharani27/Support/main/Lolita.jpg
https://raw.githubusercontent.com/RennyMaharani27/Support/main/Marsel.png
https://raw.githubusercontent.com/RennyMaharani27/Support/main/Mathilda.jpg
https://raw.githubusercontent.com/RennyMaharani27/Support/main/Rafaela.jpg

=== TANK (15) ===
https://raw.githubusercontent.com/RennyMaharani27/Tank/main/Akai.jpg
https://raw.githubusercontent.com/RennyMaharani27/Tank/main/Alice.png
https://raw.githubusercontent.com/RennyMaharani27/Tank/main/Atlas.jpg
https://raw.githubusercontent.com/RennyMaharani27/Tank/main/Barats.png
https://raw.githubusercontent.com/RennyMaharani27/Tank/main/Baxia.png
https://raw.githubusercontent.com/RennyMaharani27/Tank/main/Belerick.jpg
https://raw.githubusercontent.com/RennyMaharani27/Tank/main/Franco.png
https://raw.githubusercontent.com/RennyMaharani27/Tank/main/Gloo.png
https://raw.githubusercontent.com/RennyMaharani27/Tank/main/Grock.png
https://raw.githubusercontent.com/RennyMaharani27/Tank/main/Hilda.png
https://raw.githubusercontent.com/RennyMaharani27/Tank/main/Hylos.jpg
https://raw.githubusercontent.com/RennyMaharani27/Tank/main/Johnson.jpg
https://raw.githubusercontent.com/RennyMaharani27/Tank/main/Minotaur.jpg
https://raw.githubusercontent.com/RennyMaharani27/Tank/main/Tigreal.jpg
https://raw.githubusercontent.com/RennyMaharani27/Tank/main/Uranus.png